In [1]:
#importando pacotes úteis
import pandas as pd
import numpy as np
from sklearn.model_selection import LeaveOneOut
from sklearn import neighbors

In [2]:
dt_3apli_ruido_nominal = pd.read_csv('3apli_25ruido_25incerteza.csv');
dt_3apli_ruido_nominal

App1 - SLLC  App1 - DRAM   App1 - NET  App2 - SLLC  App2 - DRAM  \
0    Muito baixo  Muito baixo  Muito baixo  Muito baixo  Muito baixo   
1    Muito baixo  Muito baixo   Muito alto  Muito baixo  Muito baixo   
2    Muito baixo  Muito baixo  Muito baixo  Muito baixo  Muito baixo   
3    Muito baixo  Muito baixo  Muito baixo  Muito baixo  Muito baixo   
4    Muito baixo  Muito baixo  Muito baixo  Muito baixo  Muito baixo   
..           ...          ...          ...          ...          ...   
380  Muito baixo   Muito alto        Medio   Muito alto  Muito baixo   
381   Muito alto  Muito baixo  Muito baixo   Muito alto  Muito baixo   
382         Alto  Muito baixo        Baixo         Alto  Muito baixo   
383   Muito alto  Muito baixo        Baixo   Muito alto  Muito baixo   
384   Muito alto  Muito baixo  Muito baixo   Muito alto  Muito baixo   

      App2 - NET  App3 - SLLC  App3 - DRAM   App3 - NET Nivel de interferencia  
0    Muito baixo  Muito baixo  Muito baixo  Muito baixo            Muito baixo  
1    Muito baixo  Muito baixo  Muito baixo        Baixo            Muito baixo  
2    Muito baixo  Muito baixo  Muito baixo  Muito baixo            Muito baixo  
3    Muito baixo  Muito baixo  Muito baixo  Muito baixo            Muito baixo  
4    Muito baixo  Muito baixo  Muito baixo  Muito baixo            Muito baixo  
..           ...          ...          ...          ...                    ...  
380        Medio   Muito alto  Muito baixo        Medio             Muito alto  
381        Baixo   Muito alto  Muito baixo        Baixo             Muito alto  
382        Baixo         Alto  Muito baixo        Baixo             Muito alto  
383        Baixo   Muito alto  Muito baixo        Baixo             Muito alto  
384  Muito baixo   Muito alto   Muito alto   Muito alto             Muito alto  

[385 rows x 10 columns]

In [3]:
dt_3apli_ruido_nominal['Nivel de interferencia'].value_counts()

Muito baixo    226
Baixo           73
Medio           63
Alto            17
Muito alto       6
Name: Nivel de interferencia, dtype: int64

In [4]:
erro_majoritario = dt_3apli_ruido_nominal['Nivel de interferencia'].value_counts().max()/dt_3apli_ruido_nominal['Nivel de interferencia'].count()
print("erro_majoritario = ", erro_majoritario) 

erro_majoritario =  0.587012987012987


In [5]:
dict_cat = {
    'Muito baixo':0,
    'Baixo':1,
    'Medio':2,
    'Alto':3,
    'Muito alto': 4
}

In [6]:
# O K-NN só funciona com valores numéricos
dt_3apli_ruido = pd.DataFrame(columns=['App1 - SLLC', 'App1 - DRAM', 'App1 - NET', 'App2 - SLLC', 'App2 - DRAM', 'App2 - NET', 'App3 - SLLC', 'App3 - DRAM', 'App3 - NET'])
dt_3apli_ruido['App1 - SLLC'] = dt_3apli_ruido_nominal['App1 - SLLC'].map(dict_cat)
dt_3apli_ruido['App1 - DRAM'] = dt_3apli_ruido_nominal['App1 - DRAM'].map(dict_cat)
dt_3apli_ruido['App1 - NET'] = dt_3apli_ruido_nominal['App1 - NET'].map(dict_cat)
dt_3apli_ruido['App2 - SLLC'] = dt_3apli_ruido_nominal['App2 - SLLC'].map(dict_cat)
dt_3apli_ruido['App2 - DRAM'] = dt_3apli_ruido_nominal['App2 - DRAM'].map(dict_cat)
dt_3apli_ruido['App2 - NET'] = dt_3apli_ruido_nominal['App2 - NET'].map(dict_cat)
dt_3apli_ruido['App3 - SLLC'] = dt_3apli_ruido_nominal['App3 - SLLC'].map(dict_cat)
dt_3apli_ruido['App3 - DRAM'] = dt_3apli_ruido_nominal['App3 - DRAM'].map(dict_cat)
dt_3apli_ruido['App3 - NET'] = dt_3apli_ruido_nominal['App3 - NET'].map(dict_cat)
dt_category = dt_3apli_ruido_nominal['Nivel de interferencia'].map(dict_cat)
dt_target = np.array(dt_category)
dt_data = np.array(dt_3apli_ruido)
print('dt_target = ', dt_target)
print('dt_data = ', dt_data)

dt_target =  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4]
dt_data =  [[0 0 0 ... 0 0 0]
 [0 0 4 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [3 0 1 ... 3 0 1]
 [4 0 1 ... 4 0 1]
 [4 0 0 ... 4 4 4]]


In [7]:
loo = LeaveOneOut()
loo.get_n_splits(dt_data)
count_rights = [0] * 10
count_wrongs = [0] * 10
for train_index, test_index in loo.split(dt_data):
    #print("Test_index = ", test_index)
    dt_data_train = dt_data[train_index]
    dt_target_train = dt_target[train_index]
    dt_data_test = dt_data[test_index]
    dt_target_test = dt_target[test_index]
    for n_neighbors in range(1, 10, 1):
        clf = neighbors.KNeighborsClassifier(n_neighbors, weights='uniform')
        clf.fit(dt_data_train, dt_target_train)
        
        dt_z_test = clf.predict(dt_data_test)
        
        #print("n_neighbors = ", n_neighbors)
        if(dt_z_test == dt_target_test):
            #print("acertou")
            count_rights[n_neighbors] = count_rights[n_neighbors] + 1
        else:
            #print("errou")
            count_wrongs[n_neighbors] = count_wrongs[n_neighbors] + 1

In [8]:
print("Acertos = ", count_rights)
print("Erros = ", count_wrongs)

Acertos =  [0, 342, 337, 333, 343, 341, 341, 335, 335, 334]
Erros =  [0, 43, 48, 52, 42, 44, 44, 50, 50, 51]


In [9]:
n_elements = [0]
precision = [0]
for i in range(1, 10, 1):
    n_elements.append(count_rights[i] + count_wrongs[i])
    precision.append(count_rights[i]/n_elements[i])
print("n_elements = ", n_elements[1:])
print("precision = ", precision[1:])
#precision = np.true_divide(count_rights,215)
#precision

n_elements =  [385, 385, 385, 385, 385, 385, 385, 385, 385]
precision =  [0.8883116883116883, 0.8753246753246753, 0.8649350649350649, 0.8909090909090909, 0.8857142857142857, 0.8857142857142857, 0.8701298701298701, 0.8701298701298701, 0.8675324675324675]
